sudo: required
services:
  - docker

before_install:
  - docker build -t coreycosman/docker-react -f Dockerfile.dev .
script: docker run -e CI=true coreycosman/docker-react npm run test
# script:
#   - docker run USERNAME/docker-react npm run test -- --coverage
# instead should be:
#
# script:
#   - docker run -e CI=true USERNAME/docker-react npm run test
