version: 2.1
workflows:
  docker-react:
    jobs:
      build:
        working_directory: ~/docker-react
        docker:
          - image: circleci/node:11.10.1
        steps:
          - checkout
          - run:
              name: docker build
              command: docker build -t coreycosman/docker-react -f Dockerfile.dev .
          - run:
              name: docker run tests
              command: docker run -e CI=true coreycosman/docker-react npm run test -- --coverage
          - restore_cache:
              key: dependency-cache-{{ checksum "package-lock.json" }}
          - save_cache:
              key: dependency-cache-{{ checksum "package-lock.json" }}
              paths:
                - ./node_modules
